# Dockerfile for the server application
FROM gcc:latest

RUN apt-get update && apt-get install -y cmake

WORKDIR /app

COPY . .

RUN mkdir -p build && cd build && cmake .. && make

ENTRYPOINT ["./build/app"]
